### ISSUE TITLE
Profiler time and perf sheet time is not matching

### ISSUE THREAD

**Issue by mansigupta07091998** [theapache64/perf-sheet#3]
I have recorded java/kotlin method sample trace from profiler and used it for getting data through perf sheet, but the time I got for my methods in perf sheet is different when I compare the time taken by methods running on main therad shown in profiler.

**Comment by theapache64** [comment]
@mansigupta07091998 Could you share the trace files and the screenshots of the time duration you are seeing?

**Comment by mansigupta07091998** [comment]
Hi,

profiler screenshot

[image: image.png]

Also the trace file attached.

**Comment by mansigupta07091998** [comment]
checked?

**Comment by mansigupta07091998** [comment]
profiler screenshot

![image (2)](https://github.com/theapache64/perf-sheet/assets/142380290/ad41e331-bf13-434e-a377-47959a25a55a)

Also the output of the trace file using perf-sheet attached.
[app_start_final-vs-app_start_final.xlsx](https://github.com/theapache64/perf-sheet/files/15198811/app_start_final-vs-app_start_final.xlsx)

**Comment by theapache64** [comment]
@mansigupta07091998 I mean the `trace` file not the `xlsx`. Can you share it?

**Comment by mansigupta07091998** [comment]
its not allowing to attach the .trace file

**Comment by mansigupta07091998** [comment]
Hi,
attached the .trace file

**Comment by mansigupta07091998** [comment]
mailed you the trace file

**Comment by theapache64** [comment]
@mansigupta07091998 I am sorry, it didn't reach here. Can you upload it Google drive and share the link here?

**Comment by mansigupta07091998** [comment]
trace link: https://drive.google.com/file/d/1rURKkvKOszr1sG5XHTvb7VvU6pWIl-uZ/view?usp=sharing

**Comment by theapache64** [comment]
![image](https://github.com/theapache64/perf-sheet/assets/9678279/15f9daba-4def-461a-a5a1-bfb1af7df10d)

@mansigupta07091998 the table shows `totalTime` while perf-sheet shows `runningTime`, which matters more.

**Comment by mansigupta07091998** [comment]
okay, and what is meant by no. of blocks

**Comment by theapache64** [comment]
number of trace blocks (nodes) with the same name in the trace. not "thread blocked".

**Comment by theapache64** [comment]
Btw, the new version has single trace analysis added. It'll be faster than passing same trace as before and after

**Comment by theapache64** [comment]
Closing the discussion, as the issue mentioned in the title has been resolved.
